name: alfresco-dbp
version: 0.8.3
description: A Helm chart for the Alfresco Digital Business Platform
keywords:
- alfresco
- dbp
- platform
home: https://www.alfresco.com/platform
maintainers:
- name: Alfresco Platform Services Team
