dependencies:
  - name: alfresco-content-services
    version: 4.1.0
    condition: alfresco-content-services.enabled
    repository: https://kubernetes-charts.alfresco.com/incubator
  - name: alfresco-process-services
    version: 0.2.1
    condition: alfresco-process-services.enabled
    repository: https://kubernetes-charts.alfresco.com/stable
  - name: activemq
    version: ^1.1.1
    repository: https://kubernetes-charts.alfresco.com/stable
    condition: activemq.enabled
  - name: alfresco-identity-service
    version: 2.0.0
    condition: alfresco-identity-service.enabled
    repository: https://kubernetes-charts.alfresco.com/stable
  - name: nginx-ingress
    condition: nginx-ingress.enabled
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.14.0
