dependencies:
  - name: alfresco-content-services
    version: ~2.1.0
    condition: alfresco-content-services.enabled
    repository: https://kubernetes-charts.alfresco.com/stable
  - name: alfresco-infrastructure
    version: ~4.1.1
    condition: alfresco-infrastructure.enabled
    repository: https://kubernetes-charts.alfresco.com/stable
  - name: alfresco-process-services
    version: ~0.1.5
    condition: alfresco-process-services.enabled
    repository: https://kubernetes-charts.alfresco.com/stable
