# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

global:
  alfrescoRegistryPullSecrets: quay-registry-secret
  keycloak:
    resource: alfresco
    realm: alfresco
    client: alfresco
    url: "https://alfresco-identity-service.REPLACEME/auth"

alfresco-process-services:
  enabled: true
  alfresco-infrastructure:
    enabled: false
  ingress:
    protocol: http
    hostName: 'alfresco-process.REPLACEME'
  processEngine:
    environment:
      IDENTITY_SERVICE_ENABLED: "true"
      IDENTITY_SERVICE_AUTH: "https://alfresco-identity-service.REPLACEME/auth"
  resources:
    requests:
      memory: "2000Mi"
    limits:
      memory: "3000Mi"
  processWorkspace:
    ingress:
      path: "/process-workspace"
    environment:
      BASE_PATH: "./"
      APP_CONFIG_AUTH_TYPE: "OAUTH"
      APP_CONFIG_BPM_HOST: "http://alfresco-process.REPLACEME"
      APP_CONFIG_ECM_HOST: "http://alfresco-cs-repository.REPLACEME"
      APP_CONFIG_OAUTH2_HOST: "http://alfresco-identity-service.REPLACEME/auth/realms/alfresco"
      APP_CONFIG_OAUTH2_CLIENTID: "alfresco"
      APP_CONFIG_OAUTH2_REDIRECT_LOGIN: "/process-workspace/"
      APP_CONFIG_OAUTH2_REDIRECT_LOGOUT: "/process-workspace/"
      APP_CONFIG_OAUTH2_REDIRECT_SILENT_IFRAME_URI: "http://alfresco-process.REPLACEME/process-workspace/assets/silent-refresh.html"

alfresco-infrastructure:
  enabled: true
  activemq:
    persistence:
      subPath: "alfresco-infrastructure/activemq-data-infra"
  alfresco-identity-service:
    keycloak:
      postgresql:
        postgresPassword: "keycloak" #Setting this password is only needed for 1.5.0 chart version
    realm:
      alfresco:
        extraAdminUserRealmRoles:
          - "ACTIVITI_ADMIN"
          - "ACTIVITI_MODELER"
          - "ACTIVITI_USER"
        extraRealmRoles:
        - name: "ACTIVITI_USER"
        - name: "ACTIVITI_MODELER"
        - name: "ACTIVITI_ADMIN"
        extraGroups:
          - name: "hr"
          - name: "testgroup"
        extraUsers:
          - username: client
            enabled: true
            firstName: "client"
            lastName: User
            email: "client@test.com"
            credentials:
            - type: password
              value: client
            realmRoles:
              - "offline_access"
              - "uma_authorization"
              - "ACTIVITI_USER"
            clientRoles:
              account:
                - "manage-account"
                - "view-profile"
          - username: modeler
            enabled: true
            firstName: "modeler"
            lastName: User
            email: "modeler@test.com"
            credentials:
            - type: password
              value: password
            realmRoles:
              - "offline_access"
              - "uma_authorization"
              - "ACTIVITI_MODELER"
            clientRoles:
              account:
                - "manage-account"
                - "view-profile"
          - username: hruser
            enabled: true
            firstName: "hruser"
            lastName: hruser
            email: "hruser@test.com"
            credentials:
            - type: password
              value: password
            realmRoles:
              - "offline_access"
              - "uma_authorization"
              - "ACTIVITI_USER"
            clientRoles:
              account:
                - "manage-account"
                - "view-profile"
            groups:
              - "hr"
          - username: hradmin
            enabled: true
            firstName: "hradmin"
            lastName: hradmin
            email: "hradmin@test.com"
            credentials:
            - type: password
              value: password
            realmRoles:
              - "offline_access"
              - "uma_authorization"
              - "ACTIVITI_USER"
              - "ACTIVITI_ADMIN"
            clientRoles:
              account:
                - "manage-account"
                - "view-profile"
            groups:
              - "hr"
          - username: testuser
            enabled: true
            firstName: "testuser"
            lastName: testuser
            email: "testuser@test.com"
            credentials:
            - type: password
              value: password
            realmRoles:
              - "offline_access"
              - "uma_authorization"
              - "ACTIVITI_USER"
            clientRoles:
              account:
                - "manage-account"
                - "view-profile"
            groups:
              - "testgroup"
          - username: testadmin
            enabled: true
            firstName: "testadmin"
            lastName: testadmin
            email: "testadmin@test.com"
            credentials:
            - type: password
              value: password
            realmRoles:
              - "offline_access"
              - "uma_authorization"
              - "ACTIVITI_USER"
              - "ACTIVITI_ADMIN"
            clientRoles:
              account:
                - "manage-account"
                - "view-profile"
            groups:
              - "testgroup"
        client:
          webOrigins:
            - "*"
          redirectUris:
            - "*"

alfresco-content-services:
  enabled: true
  messageBroker:
    url:
    user: admin
    password: admin
  alfresco-infrastructure:
    enabled: false
    activemq:
      enabled: false
  share:
    image:
      repository: quay.io/alfresco/alfresco-dbp-share
      tag: "6.2.0"
    environment:
      JAVA_OPTS: " -Daims.enabled=true
        -Daims.realm=alfresco
        -Daims.resource=alfresco
        -Daims.publicClient=true
        -Daims.authServerUrl=\"https://alfresco-identity-service.REPLACEME/auth\""
  repository:
    image:
      repository: quay.io/alfresco/alfresco-dbp-repository
      tag: "6.2.0"
    environment:
      # The IDENTITY_SERVICE_URI should contain the details of the ingress host and port.
      IDENTITY_SERVICE_URI: "https://alfresco-identity-service.REPLACEME/auth"
      JAVA_OPTS: " -Dsolr.base.url=/solr
        -Dsolr.secureComms=none
        -Dindex.subsystem.name=solr6
        -Dalfresco.cluster.enabled=true
        -Ddeployment.method=HELM_CHART
        -Xms2000M -Xmx2000M
        -Dauthentication.chain=identity-service1:identity-service,alfrescoNtlm1:alfrescoNtlm
        -Didentity-service.enable-basic-auth=true
        -Didentity-service.authentication.validation.failure.silent=false
        -Didentity-service.auth-server-url=\"$IDENTITY_SERVICE_URI\"
        -Didentity-service.realm=alfresco
        -Didentity-service.resource=alfresco
        -Dsaml.keystore.location=/usr/local/tomcat/keystore/saml.keystore
        -Dsaml.keystore.keyMetaData.location=/usr/local/tomcat/keystore/saml-keystore-passwords.properties"
  externalHost: "alfresco-cs-repository.REPLACEME"
  networkpolicysetting:
    enabled: false
  alfresco-digital-workspace:
    APP_CONFIG_AUTH_TYPE: "OAUTH"
    APP_CONFIG_OAUTH2_HOST: "https://alfresco-identity-service.REPLACEME/auth/realms/alfresco"
    APP_CONFIG_OAUTH2_CLIENTID: "alfresco"
    APP_CONFIG_OAUTH2_IMPLICIT_FLOW: "\"true\""
    APP_CONFIG_OAUTH2_SILENT_LOGIN: "\"true\""
    APP_CONFIG_OAUTH2_REDIRECT_LOGIN: "/workspace/"
    APP_CONFIG_OAUTH2_REDIRECT_LOGOUT: "/workspace/logout"
